---
title: Open Active Staging
timezone: UTC
collections:
  booking_engines:
    title: Booking Engines
    output: true
    member: ''
  case_studies:
    title: Case Studies
    output: true
  events:
    title: Events
    output: true
  faqs:
    title: FAQs
    output: true
  members:
    title: Members
    output: true
  mentors:
    title: Mentors
    output: true
  partners:
    title: Partners
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/uploads/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
- scope:
    path: ''
    type: posts
  values:
    layout: post
    is_featured: false
    thumbnail_image: ''
    categories: About OpenActive
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    strapline: 
- scope:
    path: ''
    type: mentors
  values:
    layout: mentor
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    twitter: 
    linkedin: 
- scope:
    path: ''
    type: members
  values:
    layout: member
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    website: Web address
- scope:
    path: ''
    type: booking_engines
  values:
    layout: booking-engine
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    website: Web address
permalink: pretty
