---
title: OpenActive
timezone: UTC
collections:
  bookingsystems:
    title: Booking Systems
    output: true
  case_studies:
    title: Case Studies
    output: true
  champions:
    title: Champions
    output: true
  customers:
    title: Customers
    output: true
  dataproviders:
    title: Data Providers
    output: true
  events:
    title: Events
    output: true
  faqs:
    title: FAQs
    output: true
    categories:
    - About OpenActive
    - Community
    - How It Works
    - About OpenActive Data
  members:
    title: Members
    output: true
  mentors:
    title: Mentors
    output: true
  partners:
    title: Partners
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
    permalink: "/uploads/:path/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    is_main_navigation: false
    is_secondary_navigation: false
- scope:
    path: ''
    type: posts
  values:
    layout: post
    is_featured: false
    thumbnail_image: ''
    tags:
    - Using data
    - Publishing data
    - Accelerator
    - Collaboration
    - Leadership
    - Champions
    - Standards
    - Literacy and tools
- scope:
    path: ''
    type: case_studies
  values:
    layout: case-study
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    member: 
    strapline: 
    quote: 
    exposedData: 
- scope:
    path: ''
    type: mentors
  values:
    layout: mentor
    second-name: ''
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    twitter: 
    linkedin: 
    role: 
- scope:
    path: ''
    type: champions
  values:
    layout: champion
    second-name: ''
    thumbnail_image: "/uploads/placeholder.png"
    twitter: 
    linkedin: 
    role: 
    company: 
    link: 
- scope:
    path: ''
    type: partners
  values:
    layout: partner
    member: 
    case_study: 
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
- scope:
    path: ''
    type: dataproviders
  values:
    layout: dataprovider
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
- scope:
    path: ''
    type: members
  values:
    layout: member
    is_featured: false
    thumbnail_image: "/uploads/placeholder.png"
    bookingsystem: 
    website: Web address
- scope:
    path: ''
    type: bookingsystems
  values:
    layout: bookingsystem
    is_featured: false
    is_enabled: false
    thumbnail_image: "/uploads/placeholder.png"
    member: 
    website: Web address
- scope:
    path: ''
    type: customers
  values:
    thumbnail_image: "/uploads/placeholder.png"
    partner: 
compress_html:
  blanklines: false
  profile: false
locale: en-US
description: Helping physical activity reach everyone. OpenActive is community-led
  initiative with an ambition to help people in England get active using open data.
baseurl: 
url: https://staging.openactive.io
repository: openactive/openactive-staging
email: your-email@example.com
github_username: imaginatecreative
twitter_username: openactiveio
youtube_username: 
facebook_username: 
instagram_username: 
pinterest_username: 
medium_username: https://blog.openactive.io
markdown: kramdown
plugins:
- jekyll-feed
staticman:
  branch: master
